apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-demo-deployment
  labels:
    app: hello-demo
spec:
  selector:
    matchLabels:
      app: hello-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-demo
    spec:
      containers:
      - name: hello-demo
        image: bhargavshah86/kube-test:v0.1
        ports:
        - containerPort:81 
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-demo
spec:
  selector:
    app: hello-demo
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
      nodePort: 30081   
  type: NodePort
