--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: default
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
        - 
       image: "https:jfrog.00test.com/dckrcache/nginx:1.19"
          name: nginx
          ports: 
            - 
              containerPort: 80
          volumeMounts: 
            - 
              mountPath: /usr/share/nginx/html/
              name: nginx-index-file
      volumes: 
        - 
          configMap: 
            name: index-html-configmap
          name: nginx-index-file

