apiVersion: v1
kind: Service
metadata:
  name: greathomepage
spec:
  selector:
    app: nginx-deployment
  ports:
    - port: 80
      targetPort: 80
  externalTrafficPolicy: Local
  type: LoadBalancer
