--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-corphomepage
  namespace: default
  annotations:
    consul.hashicorp.com/connect-inject: true
spec: 
  replicas: 6
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      namespace: corporate-homepage
      labels: 
        app: nginx
    spec: 
      containers: 
        - 
          image: "jfrog-test.cnvr.in:32001/nginx:1.19"
          name: nginx
          ports: 
            - 
              containerPort: 80
          volumeMounts: 
            - 
              mountPath: /usr/share/nginx/html/
              name: nginx-index-file
      volumes: 
        - 
          configMap: 
            name: index-html-configmap
          name: nginx-index-file
       
