--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-corphomepage
  namespace: default
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      namespace: corporate-homepage
      labels: 
        app: nginx
    spec: 
      containers: 
        - 
          image: "jfrog.00test.com/dckrcache/nginx:1.21"
          name: nginx
          ports: 
            - 
              containerPort: 80
          volumeMounts: 
            - 
              mountPath: /usr/share/nginx/html/
              name: nginx-index-file
            - 
              mountPath: /usr/share/nginx/html/location/ 
              name: nginx-location-file
      volumes: 
        - 
          configMap: 
            name: index-html-configmap
          name: nginx-index-file
        - 
          configMap:
            name: location-html-configmap
          name: nginx-location-file
